### ISSUE TITLE
Add new bookmarks by default?

### ISSUE THREAD

**Issue by felciano** [grantwinney/pinboard-bookmarks-to-chrome#34]
Hi --

Thanks for making this helpful extension available. Is there a way to have it automatically add new tags that get created? That is, if I use pinboard normally and add new/custom tags for new bookmarks as needed, it is sometimes hard to remember which tags were new when I return to `pinboard-bookmarks-to-chrome` and remind myself to select them for export. Is there a way of exporting new tags by default?

Thanks!

**Comment by grantwinney** [comment]
Hi. I haven't used Pinboard in years, and don't have an account with him anymore, so there's not a whole lot I can do to modify this without risking breaking it all. 😬 

The only reason I haven't pulled it from the store is that people seem to still find it useful, or at least something to learn from I guess?

If you open a PR, I could probably merge it, but again I can't really _test_ it anymore so it'd be a bit risky. 🤞 🍀

**Comment by sfd99** [comment]
@grantwinney
just as a question...
what do you use currently,
and do you like it more than the original Pinboard?
thanks!

**Comment by grantwinney** [comment]
I guess it's safe to close this...

**Comment by grantwinney** [comment]
@sfd99 I currently use [Raindrop](https://raindrop.io/).

I hadn't used Pinboard in awhile when this issue was created, so I don't have the faintest clue what it looks like at this point. Based on what I saw before, I like Raindrop more. It has a lot of flexibility, is far easier on the eyes than what I saw years ago, and the free tier does everything I need.
